<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "actual".
 *
 * @property integer $id
 * @property string $title
 * @property integer $fk_agent
 * @property string $created_at
 * @property string $updated_at
 */
class Actual extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'actual';
    }

    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['fk_agent'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['title'], 'string', 'max' => 100],
            [['updated_at', 'created_at'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Тренинг или вебинар',
            'fk_agent' => 'Fk Agent',
            'created_at' => 'Создано',
            'updated_at' => 'Updated At',
        ];
    }
    
    public function getUser(){
        return $this->hasOne(User::className(),['id' => 'fk_agent']);
    }


    public function afterSave($insert, $changedAttributes)
   {
       parent::afterSave($insert, $changedAttributes);// TODO: Change the autogenerated stub
       Yii::$app->locator->cache->set('id',$this->id);
   }

    /**
     * @inheritdoc
     * @return ActualQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ActualQuery(get_called_class());
    }
}
