<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "aplications".
 *
 * @property integer $id
 * @property string $titlestudy
 * @property string $name
 * @property string $email
 * @property string $phone
 * @property string $text
 * @property integer $fk_agent
 * @property string $created_at
 * @property string $updated_at
 */
class Aplications extends \yii\db\ActiveRecord
{
    public $verifyCode;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'aplications';
    }

    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['text'], 'string'],
            [['name', 'email', 'phone','titlestudy'], 'required'],
            ['email', 'email'],
            [['fk_agent'], 'integer'],
            [['updated_at', 'created_at'], 'safe'],
            ['verifyCode', 'captcha', 'captchaAction' => \yii\helpers\Url::to(['main/captcha'])],
            
       ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'titlestudy' => 'Тренинг или вебинар',
            'name' => 'Имя',
            'email' => 'Email',
            'phone' => 'Телефон',
            'text' => 'Сообщение',
            'created_at' => 'Дата создания',
            'updated_at' => 'Apdated At',
        ];
    }

    public function getUser(){
        return $this->hasOne(User::className(),['id' => 'fk_agent']);
    }


    public function afterSave($insert, $changedAttributes)
   {
       parent::afterSave($insert, $changedAttributes);// TODO: Change the autogenerated stub
       Yii::$app->locator->cache->set('id',$this->id);
   }

    /**
     * @inheritdoc
     * @return AplicationsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new AplicationsQuery(get_called_class());
    }
}
