<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\helpers\Url;

/**
 * This is the model class for table "articles".
 *
 * @property integer $id
 * @property string $title
 * @property string $general_image
 * @property string $short_text
 * @property string $main_text
 * @property integer $fk_agent
 * @property string $created_at
 * @property string $updated_at
 */
class Articles extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'articles';
    }

    
    public function scenarios(){
        $scenarios = parent::scenarios();
        $scenarios['step2'] = ['general_image'];

        return $scenarios;
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['short_text', 'main_text'], 'string'],

            [['title'], 'string', 'max' => 255],
            ['general_image', 'file', 'extensions' => ['jpg','png','gif']],
            [['updated_at', 'created_at'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [

            'id' => 'ID',
            'title' => 'Название',
            'general_image' => 'Изображение',
            'short_text' => 'Короткий текст',
            'main_text' => 'Основной текст',
            'created_at' => 'Дата создания статьи',
            'updated_at' => 'Дата редактирования статьи',

        ];
    }
    public function getUser(){
        return $this->hasOne(User::className(),['id' => 'fk_agent']);
    }


    public function afterSave($insert, $changedAttributes)
   {
       parent::afterSave($insert, $changedAttributes);// TODO: Change the autogenerated stub
       Yii::$app->locator->cache->set('id',$this->id);
   }

    /**
     * @inheritdoc
     * @return ArticlesQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ArticlesQuery(get_called_class());
    }
}
