<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "comentstraining".
 *
 * @property integer $id
 * @property string $title_trainings
 * @property string $general_image
 * @property string $name
 * @property string $text
 * @property string $created_at
 */
class Comentstraining extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'comentstraining';
    }

    public function scenarios(){
        $scenarios = parent::scenarios();
        $scenarios['step2'] = ['general_image'];

        return $scenarios;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title_trainings', 'name', 'text'], 'required'],
            [['text'],  'string'],
            [['created_at'], 'safe'],
            ['general_image', 'file', 'extensions' => ['jpg','png','gif']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title_trainings' => 'Название тренинга',
            'general_image' => 'Фото',
            'name' => 'Имя и фамилия',
            'text' => 'Комментарий',
            'created_at' => 'Создано',
        ];
    }

    public function getTrainings(){
        return $this->hasOne(Trainings::className(),['title' => 'title_trainings']);
    }

    public function afterSave($insert, $changedAttributes)
   {
       parent::afterSave($insert, $changedAttributes);// TODO: Change the autogenerated stub
       Yii::$app->locator->cache->set('id',$this->id);
   }
    /**
     * @inheritdoc
     * @return ComentstrainingQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ComentstrainingQuery(get_called_class());
    }
}
