<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "price".
 *
 * @property integer $id
 * @property integer $individual
 * @property integer $child
 * @property integer $family
 * @property string $created_at
 * @property string $updated_at
 */
class Price extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'price';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['individual', 'child', 'family'], 'required'],
            [['individual', 'child', 'family'], 'integer'],
            
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'individual' => 'Индивидуальная встреча',
            'child' => 'Родители и дети',
            'family' => 'Муж и жена',
        ];
    }
    
    public function getUser(){
        return $this->hasOne(User::className(),['id' => 'fk_agent']);
    }

    public function afterSave($insert, $changedAttributes)
   {
       parent::afterSave($insert, $changedAttributes);// TODO: Change the autogenerated stub
       Yii::$app->locator->cache->set('id',$this->id);
   }

    /**
     * @inheritdoc
     * @return PriceQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new PriceQuery(get_called_class());
    }
}
