<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "psychologists".
 *
 * @property integer $id
 * @property string $name
 * @property string $general_image
 * @property string $short_text
 * @property string $about
 * @property string $email
 * @property string $phone
 * @property integer $fk_agent
 * @property string $created_at
 * @property string $updated_at
 */
class Psychologists extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'psychologists';
    }

    
    public function scenarios(){
        $scenarios = parent::scenarios();
        $scenarios['step2'] = ['general_image'];

        return $scenarios;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['short_text', 'about', 'name', 'contacts'], 'string'],
            ['general_image', 'file', 'extensions' => ['jpg','png','gif']],
            [['updated_at', 'created_at'], 'safe'],


        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Имя и Фамилия',
            'general_image' => 'Фотография',
            'short_text' => 'Корткий текст',
            'about' => 'Основной текст',
            'contacts' => 'Контактные данные',
            'created_at' => 'Дата создания',
            'updated_at' => 'Дата редактирования',
        ];
    }

    public function getUser(){
        return $this->hasOne(User::className(),['id' => 'fk_agent']);
    }


    public function afterSave($insert, $changedAttributes)
   {
       parent::afterSave($insert, $changedAttributes);// TODO: Change the autogenerated stub
       Yii::$app->locator->cache->set('id',$this->id);
   }

    /**
     * @inheritdoc
     * @return PsychologistsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new PsychologistsQuery(get_called_class());
    }
}
