<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "questions".
 *
 * @property integer $id
 * @property string $email
 * @property string $text
 * @property integer $fk_agent
 * @property string $created_at
 * @property string $updated_at
 */
class Questions extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'questions';
    }

    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'email', 'text'], 'required'],
            ['email', 'email'],
            [['updated_at', 'created_at'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Ф. И. О.',
            'email' => 'Email',
            'text' => 'Вопрос',
            'created_at' => 'Дата создания',
            'updated_at' => 'Дата редактирования',
        ];
    }
    
    public function getUser(){
        return $this->hasOne(User::className(),['id' => 'fk_agent']);
    }

   public function afterSave($insert, $changedAttributes)
   {
       parent::afterSave($insert, $changedAttributes);// TODO: Change the autogenerated stub
       Yii::$app->locator->cache->set('id',$this->id);
   }
    /**
     * @inheritdoc
     * @return QuestionsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new QuestionsQuery(get_called_class());
    }
}
