<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "subscribe".
 *
 * @property integer $id
 * @property string $email
 * @property integer $fk_agent
 * @property string $updated_at
 * @property string $created_at
 */
class Subscribe extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'subscribe';
    }

    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['email'], 'required'],
            [['email'], 'email'],
            [['email'], 'unique'],
            [['updated_at', 'created_at'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Id',
            'email' => 'Email',
            'created_at' => 'Дата создания',
            'updated_at' => 'Дата редактирования',
        ];
    }
    
    public function getUser(){
        return $this->hasOne(User::className(),['id' => 'fk_agent']);
    }


    public function afterSave($insert, $changedAttributes)
   {
       parent::afterSave($insert, $changedAttributes);// TODO: Change the autogenerated stub
       Yii::$app->locator->cache->set('id',$this->id);
   }

    /**
     * @inheritdoc
     * @return SubscribeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new SubscribeQuery(get_called_class());
    }
}
