<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "vebinars".
 *
 * @property integer $id
 * @property string $title
 * @property string $general_image
 * @property string $goal
 * @property string $date_next
 * @property string $for
 * @property string $after
 * @property string $how
 * @property integer $price
 * @property integer $fk_agent
 * @property string $created_at
 * @property string $updated_at
 */
class Vebinars extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vebinars';
    }

    public function scenarios(){
        $scenarios = parent::scenarios();
        $scenarios['step2'] = ['general_image'];

        return $scenarios;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['goal', 'main_text'], 'string'],
            [['title', 'price', 'date_next'], 'string', 'max' => 255],
            ['general_image', 'file', 'extensions' => ['jpg','png','gif']],
            [['updated_at', 'created_at'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Название',
            'general_image' => 'Изображение',
            'goal' => 'Цель',
            'date_next' => 'Ближайшая группа',
            'main text' => 'Основной текст',
            'price' => 'Цена',
            'created_at' => 'Дата создания',
            'updated_at' => 'Дата редактирования',
        ];
    }
    
    public function getUser(){
        return $this->hasOne(User::className(),['id' => 'fk_agent']);
    }
    public function getComentsvebinar(){
        return $this->hasMany(Comentsvebinar::className(),['title_vebinar' => 'title']);
    }


    public function afterSave($insert, $changedAttributes)
   {
       parent::afterSave($insert, $changedAttributes);// TODO: Change the autogenerated stub
       Yii::$app->locator->cache->set('id',$this->id);
   }

    /**
     * @inheritdoc
     * @return VebinarsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new VebinarsQuery(get_called_class());
    }
}
